version: "3"
services:
  postgres:
    container_name: postgresCerberus
    image: postgres
    environment:
      POSTGRES_USER: cerberususer
      POSTGRES_PASSWORD: cerberuspass
      PGDATA: /data/postgres
    volumes:
      - postgres_cerberus:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  pgadmin:
    container_name: pgadminCerberus
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_cerberus:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
  rabbitmq:
    container_name: rabbit_cerberus
    build: .
    environment:
      RABBITMQ_DEFAULT_USER: cerberususer
      RABBITMQ_DEFAULT_PASS: cerberuspass
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq_cerberus:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"

volumes:
  postgres_cerberus:
  pgadmin_cerberus:
  rabbitmq_cerberus:
